### ISSUE TITLE
getting Error "ValueError: The last dimension of the inputs to Dense should be defined. Found None" 

### ISSUE THREAD

**Issue by saitejatvm** [Darthholi/similarity-models#1]
Hi.. I have cloned the repo and ran the experiments_ft.py on the provided dataset, but I am getting error of 

`ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.` 

from this line `feat_ext = siam_layer(Dense(256 * n_siz, activation='relu'), 'denseall')(boxes_input_with_neighbours)`

The boxes_input_with_neighbours dimension is coming out to be as `KerasTensor(type_spec=TensorSpec(shape=(None, None, None), dtype=tf.float32, name=None), name='gather_from_indices/Reshape_3:0', description="created by layer 'gather_from_indices'")`

from the class 

`    boxes_input_with_neighbours = GatherFromIndices(mask_value=0,
                                                     include_self=True, flatten_indices_features=True) \
        ([merged_result, inp_neighs]) if neighbours > 0 else merged_result`

Attaching screenshot for reference

<img width="1791" alt="Screenshot 2021-07-16 at 1 28 19 PM" src="https://user-images.githubusercontent.com/3329351/125915668-e6a2e82b-4631-45d9-93f6-64188796fb5f.png">

**Comment by holimart** [comment]
Hi! It might be that you are using a different version of TF/Keras than this code actually needs! I believe it might be working in TF 1.something and not TF 2.something, since there were lots of breaking changes.
It should be refactorable to work in TF2 too of course :)

**Comment by saitejatvm** [comment]
Thanks, it worked. Had to switch to tensorflow-1.13 as tensorflow-gpu is having CUDA compatability issues.
