### ISSUE TITLE
Pics table missing from article_anon_a.sqlite 

### ISSUE THREAD

**Issue by saitejatvm** [Darthholi/similarity-models#2]
Getting Error 

`"from pics where docid=='{}' and ipage=={}").format(doc_id, page_n)).fetchall()
sqlite3.OperationalError: no such table: pics`

Shared data doesn't have pics table in it. 

Also Can you share the preprocessing file to create the features on the custom dataset. Thanks in advance

<img width="1786" alt="Screenshot 2021-07-20 at 12 35 45 PM" src="https://user-images.githubusercontent.com/3329351/126278457-66c26bf3-a083-4907-a81f-50018d395b37.png">
<img width="1792" alt="Screenshot 2021-07-20 at 12 36 07 PM" src="https://user-images.githubusercontent.com/3329351/126278428-1c75d795-dee0-4194-915d-8a6a2a038416.png">

**Comment by holimart** [comment]
Hello, there should be an option to not use picture data. (I can have a look at it later if it is not to be found in the args click specification.)

Ad: Share the preprocessing file to create features on a custom dataset - there is no such preprocessing file. All the feature extraction and engineering takes place in the code that is provided and takes the sqlite as input.
The only requirement is for the sqlite to contain data in the same/expected format. Sadly I cannot write custom converters from various datasets to the sqlite format.

But if you would write such an exporter, we can either
 - add it to the repo, of course,
 - or just advertise your public repository and codes in the readme here (please note that the codes have GNU affero license which requires sharing any derivative work's codes ... and I would gladly advertise Your research of course :) )

**Comment by saitejatvm** [comment]
Hey Hi..

Really appreciate your quick response.

I have used the  `--use pic` argument earlier as well as you can see in the screenshot, the problem is that the pictures are not present in the training data shared https://www.kaggle.com/martholi/anonymized-invoices.

I am able to run the code with` --use pic `argument disabled due to which **Image Features** won't be considered. Can you point me to the Repo where i would be able to get Image/Picture data as well.

Thanks in advance..

**Comment by holimart** [comment]
Hi,

you are welcome.

Thanks for the clarification - the picture data are not available at all, since the dataset needs to be anonymized and the anonymization includes omitting the image data (I should probably write it somewhere).

But it should not matter - the results are reproducible on the anonymized dataset :)
