### ISSUE TITLE
How to view the PDF files in the SQL database

### ISSUE THREAD

**Issue by MuhammadAliShahzad** [Darthholi/similarity-models#4]
Hi,

I am trying to view the pdf files embedded in the SQL database but unfortunately I am not able to extract them in a viewable format. I have also tried segmenting code from your compute_index function [here](https://github.com/Darthholi/similarity-models/blob/114c52ce0017dab9543f4793884360fe1b4e33e0/utils/sqlite_experiment_generator.py#L930) but to no avail. The pages are returned as a list with byte array. The line [here ](https://github.com/Darthholi/similarity-models/blob/114c52ce0017dab9543f4793884360fe1b4e33e0/utils/sqlite_experiment_generator.py#L960) fails because the code tries to get the shape of byte array. I would appreciate your response.

Kind Regards,

**Comment by holimart** [comment]
Duplicated https://github.com/Darthholi/similarity-models/issues/2
